### ISSUE TITLE
Running `dbt build //...` in arbitrary repositories (e.g. libsupcxx) fails with error related to xilinx rules.

### ISSUE THREAD

**Issue by jfrohnhofen** [daedaleanai/dbt-rules#30]
E.g. running `dbt build //... cc-toolchain=x86_64-libsupcxx` in libsupcxx fails with:
`[169/232] Exporting simulator IP for xsim to /home/.../BUILD/OUTPUT-B67DFF84/dbt-rules/xilinx
FAILED: /.../BUILD/OUTPUT-B67DFF84/dbt-rules/xilinx/dummy 
This target only supports questa. xsim is not supported.`

I think this is because the xilinx rules export a target `//dbt-rules/xilinx/ExportSimulatorIp`.
If the xilinx rules can't stay silent in non-HW related repos, they should not be part of the generic dbt-rules.

**Comment by ljanyst** [comment]
I am not sure I agree with this. You can always say `//libsupcxx/...`. I will think about it.
